### ISSUE TITLE
Should dijit's _WidgetBase._attrToDom support textContent

### ISSUE THREAD

**Issue by schallm** [dojo/dijit#144]
innerText is not a cross-browser supported attribute. `_WidgetBase._attrToDom` accepts innerText as the `type` of a command to put text into node.

The implementation doesn't actually use the innerText property:

```js
	case "innerText":
		mapNode.innerHTML = "";
		mapNode.appendChild(this.ownerDocument.createTextNode(value));
		break;
```

We are attempting to make sure we don't us innerText anywhere in our code base.  It would be nice if textContent was accepted here as well:

```js
	case "textContent":
	case "innerText":
		mapNode.innerHTML = "";
		mapNode.appendChild(this.ownerDocument.createTextNode(value));
		break;
```

Code above could potentially be simplified to set textContent as well?

**Comment by dylans** [comment]
innerText and textContent are not identical, the classic example given is:

> innerText returns the visible text contained in a node, while textContent returns the full text. For example, on the following HTML <span>Hello <span style="display: none;">World</span></span>, innerText will return 'Hello', while textContent will return 'Hello World'.

So, if we want to support both, I would suggest at a minimum that we have separate case statements, even if they both currently do the same thing. e.g.:

```
	case "textContent":
		mapNode.innerHTML = "";
		mapNode.appendChild(this.ownerDocument.createTextNode(value));
		break;
	case "innerText":
		mapNode.innerHTML = "";
		mapNode.appendChild(this.ownerDocument.createTextNode(value));
		break;
```

That way if someone in the future wants to make them behave differently, the expectation is not that they are the same.

@schallm if you raise a PR for the above we can review and land it. Thanks!

**Comment by wkeese** [comment]
I misnamed the `type`, I should have called it "textContent" from the beginning rather than "innerText".  I probably just got confused about which one was the standard.

I don't see any reason to support two flags, except for saying the "textContent" is the recommended API and "innerText" is deprecated.

Note that `_WidgetBase._attrToDom` is about setting the value, not getting the value, so I don't think there are any issues about hidden text or whitespace, i.e. I can't conceive of a future where the two flags could do different things.

**Comment by schallm** [comment]
Opened pull request https://github.com/dojo/dijit/pull/147

Let me know if that is what your comments meant.

**Comment by msssk** [comment]
Closing this as #147 has been merged.
